apiVersion: v2
name: goldengate-helm-chart
description: Helm chart for Oracle GoldenGate
type: application
version: 1.0.0
appVersion: 23c
icon: https://example.com/path/to/icon.png  # Replace with a valid URL to an icon