apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: goldengate
data:
  ggserr.log: |
    # Custom error logs configuration
    LogLevel: Info
  other.config: |
    # Additional configurations