apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-goldengate-config
  labels:
    app: goldengate
data:
  OGG_HOME: "{{ .Values.config.OGG_HOME }}"
  #PATH: "{{ .Values.config.OGG_HOME }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"