apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-goldengate
  labels:
    app: goldengate
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: goldengate
  template:
    metadata:
      labels:
        app: goldengate
    spec:
      containers:
        - name: goldengate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: OGG_HOME
              value: "{{ .Values.config.OGG_HOME }}"
            - name: OGG_ADMIN_USERNAME
              value: "{{ .Values.config.AdminUsername }}"
            - name: OGG_ADMIN_PASSWORD
              value: "{{ .Values.config.AdminPassword }}"
          volumeMounts:
            - name: ogg-data
              mountPath: /u01/app/ogg/data
      volumes:
        - name: ogg-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc