# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goldengate.fullname" . }}
  labels:
    app: {{ include "goldengate.name" . }}
    chart: {{ include "goldengate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "goldengate.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "goldengate.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        #fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: OGG_HOME
          value: {{ .Values.config.oggHome }}
        - name: OGG_DEPLOYMENT
          value: {{ .Values.config.oggDeployment }}
        - name: OGG_TEMP
          value: {{ .Values.config.oggTemp }}
        - name: OGG_SCRPTS
          value: {{ .Values.config.oggScripts }}    
        - name: OGG_USERNAME
          value: {{ .Values.config.oggCredentials.username }}
        - name: OGG_PASSWORD
          value: {{ .Values.config.oggCredentials.password }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: goldengate-data
          mountPath: {{ .Values.config.oggHome }}
        - name: goldengate-deployment
          mountPath: {{ .Values.config.oggDeployment }}
      volumes:
      - name: goldengate-data
        persistentVolumeClaim:
          claimName: {{ include "goldengate.fullname" . }}-pvc
      - name: goldengate-deployment
        persistentVolumeClaim:
          claimName: {{ include "goldengate.fullname" . }}-u02-pvc
      - name: goldengate-temp
        persistentVolumeClaim:
          claimName: {{ include "goldengate.fullname" . }}-u03-pvc
