apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goldengate.fullname" . }}-pvc
  labels:
    app: {{ include "goldengate.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size.goldengate }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goldengate.fullname" . }}-u02-pvc
  labels:
    app: {{ include "goldengate.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size.goldengate }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goldengate.fullname" . }}-u03-pvc
  labels:
    app: {{ include "goldengate.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size.goldengate }}
  storageClassName: {{ .Values.persistence.storageClass }}