apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.oggData.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.oggData.size }}
  storageClassName: {{ .Values.pv.oggData.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.oggDeploymentHome.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.oggDeploymentHome.size }}
  storageClassName: {{ .Values.pv.oggDeploymentHome.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.oggTemporaryFiles.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.oggTemporaryFiles.size }}
  storageClassName: {{ .Values.pv.oggTemporaryFiles.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.oggDeploymentScripts.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.oggDeploymentScripts.size }}
  storageClassName: {{ .Values.pv.oggTemporaryFiles.storageClass }}