apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.oggData.name }}
  labels:
    app: goldengate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pv.oggData.size }}"
  {{- if .Values.pv.oggData.storageClass }}
  storageClassName: "{{ .Values.pv.oggData.storageClass }}"
  {{- end }}
  {{- if .Values.persistence.existingClaim }}
  volumeName: "{{ .Values.persistence.existingClaim }}"
  {{- end }}