apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: goldengate
type: Opaque
data:
  admin-username: {{ .Values.config.AdminUsername | b64enc }}
  admin-password: {{ .Values.config.AdminPassword | b64enc }}