apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-goldengate-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: goldengate
type: Opaque
stringData:
  OGG_ADMIN_USERNAME: "{{ .Values.secrets.adminUsername }}"
  OGG_ADMIN_PASSWORD: "{{ .Values.secrets.adminPassword }}"