apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-goldengate
  labels:
    app: goldengate
spec:
  type: {{ .Values.service.type }}  # ClusterIP, LoadBalancer, etc.
  ports:
    - name: https
      port: {{ .Values.service.port }}  # The port exposed by the service
      targetPort: {{ .Values.service.targetPort }}  # Must match the container's port in Deployment.yaml
      protocol: TCP
  selector:
    app: goldengate  # Ensures traffic routes to the correct pods